/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import java.awt.Color;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;

/**
 *
 * @author james
 */
public class PrincipalC extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalC
     */
    public PrincipalC() {
        initComponents();
    }

    //Getters y setters
    
    public JLabel getLbCliYProv() {
        return LbCliYProv;
    }

    public void setLbCliYProv(JLabel LbCliYProv) {
        this.LbCliYProv = LbCliYProv;
    }

    public JLabel getLbProdYSer() {
        return LbProdYSer;
    }

    public void setLbProdYSer(JLabel LbProdYSer) {
        this.LbProdYSer = LbProdYSer;
    }

    public JLabel getLbSalir() {
        return LbSalir;
    }

    public void setLbSalir(JLabel LbSalir) {
        this.LbSalir = LbSalir;
    }

    public JDesktopPane getDtPrincipal() {
        return DtPrincipal;
    }

    public void setDtPrincipal(JDesktopPane DtPrincipal) {
        this.DtPrincipal = DtPrincipal;
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LbPrincipal = new javax.swing.JLabel();
        LbProdYSer = new javax.swing.JLabel();
        LbCliYProv = new javax.swing.JLabel();
        LbSalir = new javax.swing.JLabel();
        DtPrincipal = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(235, 235, 244));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(33, 49, 91));

        jLabel1.setFont(new java.awt.Font("Roboto Mono SemiBold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/ICONOS/edita.png"))); // NOI18N
        jLabel1.setText(" Prueba");

        LbPrincipal.setBackground(new java.awt.Color(33, 49, 91));
        LbPrincipal.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LbPrincipal.setForeground(new java.awt.Color(184, 199, 206));
        LbPrincipal.setText(" Principal");
        LbPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbPrincipal.setOpaque(true);
        LbPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbPrincipalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LbPrincipalMouseEntered(evt);
            }
        });

        LbProdYSer.setBackground(new java.awt.Color(33, 49, 91));
        LbProdYSer.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LbProdYSer.setForeground(new java.awt.Color(184, 199, 206));
        LbProdYSer.setText(" Productos & Servicios");
        LbProdYSer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbProdYSer.setOpaque(true);
        LbProdYSer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbProdYSerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LbProdYSerMouseEntered(evt);
            }
        });

        LbCliYProv.setBackground(new java.awt.Color(33, 49, 91));
        LbCliYProv.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LbCliYProv.setForeground(new java.awt.Color(184, 199, 206));
        LbCliYProv.setText(" Clientes & Proveedores");
        LbCliYProv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbCliYProv.setOpaque(true);
        LbCliYProv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbCliYProvMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LbCliYProvMouseEntered(evt);
            }
        });

        LbSalir.setBackground(new java.awt.Color(33, 49, 91));
        LbSalir.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LbSalir.setForeground(new java.awt.Color(184, 199, 206));
        LbSalir.setText(" Salir");
        LbSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbSalir.setOpaque(true);
        LbSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LbSalirMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LbPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LbProdYSer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LbCliYProv, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
            .addComponent(LbSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(LbProdYSer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbCliYProv, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 463, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 750));

        DtPrincipal.setBackground(new java.awt.Color(240, 240, 255));

        javax.swing.GroupLayout DtPrincipalLayout = new javax.swing.GroupLayout(DtPrincipal);
        DtPrincipal.setLayout(DtPrincipalLayout);
        DtPrincipalLayout.setHorizontalGroup(
            DtPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
        );
        DtPrincipalLayout.setVerticalGroup(
            DtPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        jPanel1.add(DtPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 1100, 670));

        jPanel3.setBackground(new java.awt.Color(33, 49, 91));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 1100, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LbProdYSerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbProdYSerMouseClicked
        // TODO add your handling code here:
        LbProdYSer.setBackground(new java.awt.Color(14, 22, 40));
        LbPrincipal.setBackground(new java.awt.Color(33, 49, 91));
        LbCliYProv.setBackground(new java.awt.Color(33, 49, 91));
        LbSalir.setBackground(new java.awt.Color(33, 49, 91));
    }//GEN-LAST:event_LbProdYSerMouseClicked

    private void LbPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbPrincipalMouseClicked
        // TODO add your handling code here:
        LbProdYSer.setBackground(new java.awt.Color(33, 49, 91));
        LbPrincipal.setBackground(new java.awt.Color(14, 22, 40));
        LbCliYProv.setBackground(new java.awt.Color(33, 49, 91));
        LbSalir.setBackground(new java.awt.Color(33, 49, 91));
    }//GEN-LAST:event_LbPrincipalMouseClicked

    private void LbCliYProvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbCliYProvMouseClicked
        // TODO add your handling code here:
        LbProdYSer.setBackground(new java.awt.Color(33, 49, 91));
        LbPrincipal.setBackground(new java.awt.Color(33, 49, 91));
        LbCliYProv.setBackground(new java.awt.Color(14, 22, 40));
        LbSalir.setBackground(new java.awt.Color(33, 49, 91));        
    }//GEN-LAST:event_LbCliYProvMouseClicked

    private void LbSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbSalirMouseClicked
        // TODO add your handling code here:
        LbProdYSer.setBackground(new java.awt.Color(33, 49, 91));
        LbPrincipal.setBackground(new java.awt.Color(33, 49, 91));
        LbCliYProv.setBackground(new java.awt.Color(33, 49, 91));
        LbSalir.setBackground(new java.awt.Color(14, 22, 40));         
    }//GEN-LAST:event_LbSalirMouseClicked

    private void LbSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbSalirMouseEntered
        // TODO add your handling code here:
        LbProdYSer.setBackground(new java.awt.Color(33, 49, 91));
        LbPrincipal.setBackground(new java.awt.Color(33, 49, 91));
        LbCliYProv.setBackground(new java.awt.Color(33, 49, 91));
        LbSalir.setBackground(new java.awt.Color(14, 22, 40)); 
    }//GEN-LAST:event_LbSalirMouseEntered

    private void LbCliYProvMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbCliYProvMouseEntered
        // TODO add your handling code here:ç
        // TODO add your handling code here:
        LbProdYSer.setBackground(new java.awt.Color(33, 49, 91));
        LbPrincipal.setBackground(new java.awt.Color(33, 49, 91));
        LbCliYProv.setBackground(new java.awt.Color(14, 22, 40));
        LbSalir.setBackground(new java.awt.Color(33, 49, 91));            
    }//GEN-LAST:event_LbCliYProvMouseEntered

    private void LbProdYSerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbProdYSerMouseEntered
        // TODO add your handling code here:
        LbProdYSer.setBackground(new java.awt.Color(14, 22, 40));
        LbPrincipal.setBackground(new java.awt.Color(33, 49, 91));
        LbCliYProv.setBackground(new java.awt.Color(33, 49, 91));
        LbSalir.setBackground(new java.awt.Color(33, 49, 91));        
    }//GEN-LAST:event_LbProdYSerMouseEntered

    private void LbPrincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbPrincipalMouseEntered
        // TODO add your handling code here:
        LbProdYSer.setBackground(new java.awt.Color(33, 49, 91));
        LbPrincipal.setBackground(new java.awt.Color(14, 22, 40));
        LbCliYProv.setBackground(new java.awt.Color(33, 49, 91));
        LbSalir.setBackground(new java.awt.Color(33, 49, 91));        
    }//GEN-LAST:event_LbPrincipalMouseEntered

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DtPrincipal;
    private javax.swing.JLabel LbCliYProv;
    private javax.swing.JLabel LbPrincipal;
    private javax.swing.JLabel LbProdYSer;
    private javax.swing.JLabel LbSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
