/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA.CRUD;

import MODELO.Validaciones;
import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author james
 */
public class VCrearCliente extends javax.swing.JInternalFrame {

    protected Validaciones validaciones = new Validaciones();
    /**
     * Creates new form VOpcionesProd
     */
    public VCrearCliente() {
        initComponents();
        quitarBarra();
        Validar();
    }

    
    public void quitarBarra(){
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
    }        
    
    
    public void Validar(){
        validaciones.createFilteredField(TxtCelular, 10, Validaciones.MATCH_NUMEROS);
        validaciones.createFilteredField(Txttelefono, 10, Validaciones.MATCH_NUMEROS);
        validaciones.createFilteredField(TxtCorreo, 50, Validaciones.MATCH_EMAILS);
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtDireccion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        CbTipoId = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        CbCiudad = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        TxtAliasSuc = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        CbProvincia = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        TxtCodSucursal = new javax.swing.JTextField();
        BtnGuardarCli = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        Txttelefono = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        TxtCelular = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        TxtCorreo = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(1120, 670));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(33, 49, 91));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 65)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CLIENTES");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(787, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 120));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator7.setForeground(new java.awt.Color(33, 49, 91));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 340, 10));

        jSeparator8.setForeground(new java.awt.Color(33, 49, 91));
        jPanel3.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 180, 10));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setText("Tipo de Identificación:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setText("Identificacion:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        TxtId.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TxtId.setBorder(null);
        jPanel3.add(TxtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 220, 30));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel7.setText("Nombres / Razon Social:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 30));

        TxtDireccion.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TxtDireccion.setBorder(null);
        jPanel3.add(TxtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 500, 30));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel12.setText("DATOS BASICOS");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        CbTipoId.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        CbTipoId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cedula", "RUC", "Pasaporte", "Identificacion del Exterior", "Placa" }));
        jPanel3.add(CbTipoId, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 190, 30));

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel13.setText("Direccion:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel14.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel14.setText("Alias Sucursal:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel16.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel16.setText("Telefono:");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        CbCiudad.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        CbCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin Especificar" }));
        jPanel3.add(CbCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 200, 30));

        jLabel19.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel19.setText("Celular:");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, -1));

        jLabel20.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel20.setText("Provincia:");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        TxtAliasSuc.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TxtAliasSuc.setBorder(null);
        jPanel3.add(TxtAliasSuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 180, 30));

        jLabel21.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel21.setText("Correo:");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, -1, -1));

        CbProvincia.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        CbProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin Especificar", "Azuay                                                                                                                                                ", "Bolivar                                                                                                                                       ", "Cañar", "Carchi", "Chimborazo", "Cotopaxi", "Esmeraldas", "Exterior", "Galapagos", "Guayas", "Imbabura", "Loja", "Los Rios", "Manabi", "Morona Santiago", "Napo", "Orellana", "Pastaza", "Pichincha", "Santa Elena", "Santo Domingo", "Sucumbios", "Tungurahua", "Zamora Chinchipe" }));
        CbProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbProvinciaActionPerformed(evt);
            }
        });
        jPanel3.add(CbProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 190, 30));

        jLabel22.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel22.setText("Ciudad:");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, -1, -1));

        TxtCodSucursal.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TxtCodSucursal.setBorder(null);
        jPanel3.add(TxtCodSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 100, 30));

        BtnGuardarCli.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BtnGuardarCli.setText("Guardar");
        jPanel3.add(BtnGuardarCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 420, 110, 40));

        jSeparator9.setForeground(new java.awt.Color(33, 49, 91));
        jPanel3.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 220, 10));

        jSeparator10.setForeground(new java.awt.Color(33, 49, 91));
        jPanel3.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 100, 10));

        jLabel17.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel17.setText("Codigo Sucursal:");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, -1));

        TxtNombre.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TxtNombre.setBorder(null);
        jPanel3.add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 340, 30));

        Txttelefono.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        Txttelefono.setBorder(null);
        jPanel3.add(Txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 170, 30));

        jSeparator12.setForeground(new java.awt.Color(33, 49, 91));
        jPanel3.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 180, 10));

        TxtCelular.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TxtCelular.setBorder(null);
        jPanel3.add(TxtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 160, 30));

        jSeparator13.setForeground(new java.awt.Color(33, 49, 91));
        jPanel3.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 170, 10));

        TxtCorreo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TxtCorreo.setBorder(null);
        jPanel3.add(TxtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 330, 30));

        jSeparator14.setForeground(new java.awt.Color(33, 49, 91));
        jPanel3.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 330, 10));

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel15.setText("MATRIZ");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jSeparator15.setForeground(new java.awt.Color(33, 49, 91));
        jPanel3.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 500, 10));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 1070, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CbProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbProvinciaActionPerformed
        // TODO add your handling code here:
        int prov = CbProvincia.getSelectedIndex();
        switch(prov){
            case 0: 
                    CbCiudad.removeAllItems();
                    CbCiudad.addItem("Sin Especificar");
            break;
            case 1: 
                    CbCiudad.removeAllItems();
                    CbCiudad.addItem("Sin Especificar");
                    CbCiudad.addItem("Camilo Ponce Enriquez");
                    CbCiudad.addItem("Chordeleg");
                    CbCiudad.addItem("Cuenca");
                    CbCiudad.addItem("El Pan");
                    CbCiudad.addItem("Giron");
                    CbCiudad.addItem("Guachapala");
                    CbCiudad.addItem("Gualaceo");
                    CbCiudad.addItem("Nabon");
                    CbCiudad.addItem("Oña");
                    CbCiudad.addItem("Paute");
                    CbCiudad.addItem("Pucara");
                    CbCiudad.addItem("San Fernando");
                    CbCiudad.addItem("Santa Isabel");
                    CbCiudad.addItem("Sevilla de Oro");
                    CbCiudad.addItem("Sigsig");
            break;
            case 2: 
                    CbCiudad.removeAllItems();
                    CbCiudad.addItem("Sin Especificar");
                    CbCiudad.addItem("Caluma");
                    CbCiudad.addItem("Chillanes");
                    CbCiudad.addItem("Chimbo");
                    CbCiudad.addItem("Echeandia");
                    CbCiudad.addItem("Guaranda");
                    CbCiudad.addItem("Las Naves");
                    CbCiudad.addItem("San Miguel");
            break;
            case 3: 
                    CbCiudad.removeAllItems();
                    CbCiudad.addItem("Sin Especificar");
                    CbCiudad.addItem("Azogues");
                    CbCiudad.addItem("Biblian");
                    CbCiudad.addItem("Cañar");
                    CbCiudad.addItem("Deleg");
                    CbCiudad.addItem("El Tambo");
                    CbCiudad.addItem("La Troncal");
                    CbCiudad.addItem("Suscal");
            break;
            case 4: System.out.println("caso 1");
            break;
            case 5: System.out.println("caso 1");
            break;
            case 6: System.out.println("caso 1");
            break;
            case 7: System.out.println("caso 1");
            break;
            case 8: System.out.println("caso 1");
            break;
            case 9: System.out.println("caso 1");
            break;
            case 10: System.out.println("caso 1");
            break;
            case 11: System.out.println("caso 1");
            break;
            case 12: System.out.println("caso 1");
            break;
            case 13: System.out.println("caso 1");
            break;
            case 14: System.out.println("caso 1");
            break;
            case 15: System.out.println("caso 1");
            break;
            case 16: System.out.println("caso 1");
            break;
            case 17: System.out.println("caso 1");
            break;
            case 18: System.out.println("caso 1");
            break;
            case 19: System.out.println("caso 1");
            break;
            case 20: System.out.println("caso 1");
            break;
            case 21: System.out.println("caso 1");
            break;
            case 22: System.out.println("caso 1");
            break;
            case 23: System.out.println("caso 1");
            break;
        }
    }//GEN-LAST:event_CbProvinciaActionPerformed

    public JButton getBtnGuardarCli() {
        return BtnGuardarCli;
    }

    public void setBtnGuardarCli(JButton BtnGuardarCli) {
        this.BtnGuardarCli = BtnGuardarCli;
    }
  
    public JComboBox<String> getCbCiudad() {
        return CbCiudad;
    }

    public void setCbCiudad(JComboBox<String> CbCiudad) {
        this.CbCiudad = CbCiudad;
    }

    public JComboBox<String> getCbProvincia() {
        return CbProvincia;
    }

    public void setCbProvincia(JComboBox<String> CbProvincia) {
        this.CbProvincia = CbProvincia;
    }

    public JComboBox<String> getCbTipoId() {
        return CbTipoId;
    }

    public void setCbTipoId(JComboBox<String> CbTipoId) {
        this.CbTipoId = CbTipoId;
    }

    public JTextField getTxtAliasSuc() {
        return TxtAliasSuc;
    }

    public void setTxtAliasSuc(JTextField TxtAliasSuc) {
        this.TxtAliasSuc = TxtAliasSuc;
    }

    public JTextField getTxtCelular() {
        return TxtCelular;
    }

    public void setTxtCelular(JTextField TxtCelular) {
        this.TxtCelular = TxtCelular;
    }

    public JTextField getTxtCodSucursal() {
        return TxtCodSucursal;
    }

    public void setTxtCodSucursal(JTextField TxtCodSucursal) {
        this.TxtCodSucursal = TxtCodSucursal;
    }

    public JTextField getTxtCorreo() {
        return TxtCorreo;
    }

    public void setTxtCorreo(JTextField TxtCorreo) {
        this.TxtCorreo = TxtCorreo;
    }

    public JTextField getTxtId() {
        return TxtId;
    }

    public void setTxtId(JTextField TxtId) {
        this.TxtId = TxtId;
    }

    public JTextField getTxtNombre() {
        return TxtNombre;
    }

    public void setTxtNombre(JTextField TxtNombre) {
        this.TxtNombre = TxtNombre;
    }

    public JTextField getTxtDireccion() {
        return TxtDireccion;
    }

    public void setTxtDireccion(JTextField TxtDireccion) {
        this.TxtDireccion = TxtDireccion;
    }

    public JTextField getTxttelefono() {
        return Txttelefono;
    }

    public void setTxttelefono(JTextField Txttelefono) {
        this.Txttelefono = Txttelefono;
    }

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardarCli;
    private javax.swing.JComboBox<String> CbCiudad;
    private javax.swing.JComboBox<String> CbProvincia;
    private javax.swing.JComboBox<String> CbTipoId;
    private javax.swing.JTextField TxtAliasSuc;
    private javax.swing.JTextField TxtCelular;
    private javax.swing.JTextField TxtCodSucursal;
    private javax.swing.JTextField TxtCorreo;
    private javax.swing.JTextField TxtDireccion;
    private javax.swing.JTextField TxtId;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField Txttelefono;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
