/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA.CRUD;

import MODELO.Validaciones;
import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author james
 */
public class VCrearFactura extends javax.swing.JInternalFrame {

    protected Validaciones validaciones = new Validaciones();
    /**
     * Creates new form VOpcionesProd
     */
    public VCrearFactura() {
        initComponents();
        quitarBarra();
        Validar();
    }

    
    public void quitarBarra(){
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
    }        
    
    
    public void Validar(){
        validaciones.createFilteredField(TxtCelular, 10, Validaciones.MATCH_NUMEROS);
        validaciones.createFilteredField(Txttelefono, 10, Validaciones.MATCH_NUMEROS);
        validaciones.createFilteredField(TxtCorreo, 50, Validaciones.MATCH_EMAILS);
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        CbCiudad = new javax.swing.JComboBox<>();
        TxtAliasSuc = new javax.swing.JTextField();
        TxtCodSucursal = new javax.swing.JTextField();
        BtnGuardarCli = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TxtId1 = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        TxtId2 = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        TxtId3 = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        TxtId4 = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        CbTipoId = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        TxtId = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        TxtDireccion = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        TxtAliasSuc1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TxtCodSucursal1 = new javax.swing.JTextField();
        jSeparator20 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        Txttelefono = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        TxtCelular = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        TxtCorreo = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        CbProvincia = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        CbCiudad1 = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(1120, 670));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(33, 49, 91));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 65)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FACTURA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(797, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 120));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator8.setForeground(new java.awt.Color(33, 49, 91));
        jPanel3.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 180, 10));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setText("Ambiente:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setText("Secuencial:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, -1, -1));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel12.setText("NUEVA FACTURA");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Seleccione un resultado:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));

        jLabel14.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel14.setText("Sucursal:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, -1, -1));

        CbCiudad.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        CbCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin Especificar" }));
        jPanel3.add(CbCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 230, 30));

        TxtAliasSuc.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TxtAliasSuc.setBorder(null);
        jPanel3.add(TxtAliasSuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 180, 30));

        TxtCodSucursal.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TxtCodSucursal.setBorder(null);
        jPanel3.add(TxtCodSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 210, 30));

        BtnGuardarCli.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BtnGuardarCli.setText("Guardar");
        jPanel3.add(BtnGuardarCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 450, 110, 40));

        jSeparator10.setForeground(new java.awt.Color(33, 49, 91));
        jPanel3.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 210, 10));

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel15.setText("DATOS DEL COMPRADOR");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        jPanel3.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel8.setText("Fecha:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel9.setText("Tipo:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel10.setText("Punto de Emision:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        TxtId1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TxtId1.setBorder(null);
        jPanel3.add(TxtId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 170, 30));

        jSeparator11.setForeground(new java.awt.Color(33, 49, 91));
        jPanel3.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 170, 10));

        TxtId2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TxtId2.setBorder(null);
        jPanel3.add(TxtId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 170, 30));

        jSeparator16.setForeground(new java.awt.Color(33, 49, 91));
        jPanel3.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 170, 10));

        TxtId3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TxtId3.setBorder(null);
        jPanel3.add(TxtId3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 170, 30));

        jSeparator17.setForeground(new java.awt.Color(33, 49, 91));
        jPanel3.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 170, 10));

        TxtId4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TxtId4.setBorder(null);
        jPanel3.add(TxtId4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 100, 170, 30));

        jSeparator18.setForeground(new java.awt.Color(33, 49, 91));
        jPanel3.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 130, 170, 10));

        jButton1.setText("jButton1");
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 190, 40, -1));

        jLabel23.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel23.setText("Cliente:");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jButton2.setText("jButton1");
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 40, -1));

        jButton3.setText("jButton1");
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 190, 40, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel7.setText("Tipo de Identificación:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        CbTipoId.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        CbTipoId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cedula", "RUC", "Pasaporte", "Identificacion del Exterior", "Placa" }));
        jPanel3.add(CbTipoId, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 200, 30));

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel11.setText("Identificacion:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, -1, -1));

        TxtId.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TxtId.setBorder(null);
        jPanel3.add(TxtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 280, 30));

        jSeparator9.setForeground(new java.awt.Color(33, 49, 91));
        jPanel3.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, 280, 10));

        jLabel24.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel24.setText("Nombres / Razon Social:");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, 30));

        TxtNombre.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TxtNombre.setBorder(null);
        jPanel3.add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 310, 30));

        jSeparator7.setForeground(new java.awt.Color(33, 49, 91));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 310, 10));

        jLabel25.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel25.setText("Direccion:");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, -1, -1));

        TxtDireccion.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TxtDireccion.setBorder(null);
        jPanel3.add(TxtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 390, 30));

        jSeparator15.setForeground(new java.awt.Color(33, 49, 91));
        jPanel3.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, 390, 10));

        jLabel26.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel26.setText("Alias Sucursal:");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jSeparator19.setForeground(new java.awt.Color(33, 49, 91));
        jPanel3.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 180, 10));

        TxtAliasSuc1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TxtAliasSuc1.setBorder(null);
        jPanel3.add(TxtAliasSuc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 180, 30));

        jLabel17.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel17.setText("Codigo Sucursal:");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, -1, -1));

        TxtCodSucursal1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TxtCodSucursal1.setBorder(null);
        jPanel3.add(TxtCodSucursal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 330, 100, 30));

        jSeparator20.setForeground(new java.awt.Color(33, 49, 91));
        jPanel3.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, 100, 10));

        jLabel16.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel16.setText("Telefono:");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        Txttelefono.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        Txttelefono.setBorder(null);
        jPanel3.add(Txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 170, 30));

        jSeparator12.setForeground(new java.awt.Color(33, 49, 91));
        jPanel3.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 180, 10));

        jLabel19.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel19.setText("Celular:");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, -1, -1));

        jSeparator13.setForeground(new java.awt.Color(33, 49, 91));
        jPanel3.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 170, 10));

        TxtCelular.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TxtCelular.setBorder(null);
        jPanel3.add(TxtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 160, 30));

        jLabel21.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel21.setText("Correo:");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, -1, -1));

        TxtCorreo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TxtCorreo.setBorder(null);
        jPanel3.add(TxtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, 330, 30));

        jSeparator14.setForeground(new java.awt.Color(33, 49, 91));
        jPanel3.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, 330, 10));

        jLabel20.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel20.setText("Provincia:");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        CbProvincia.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        CbProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin Especificar", "Azuay                                                                                                                                                ", "Bolivar                                                                                                                                       ", "Cañar", "Carchi", "Chimborazo", "Cotopaxi", "El Oro", "Esmeraldas", "Exterior", "Galapagos", "Guayas", "Imbabura", "Loja", "Los Rios", "Manabi", "Morona Santiago", "Napo", "Orellana", "Pastaza", "Pichincha", "Santa Elena", "Santo Domingo", "Sucumbios", "Tungurahua", "Zamora Chinchipe" }));
        CbProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbProvinciaActionPerformed(evt);
            }
        });
        jPanel3.add(CbProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 190, 30));

        jLabel22.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel22.setText("Ciudad:");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, -1, -1));

        CbCiudad1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        CbCiudad1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin Especificar" }));
        jPanel3.add(CbCiudad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 200, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 1070, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CbProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbProvinciaActionPerformed
        // TODO add your handling code here:
        int prov = CbProvincia.getSelectedIndex();
        switch(prov){
            case 0:
            CbCiudad.removeAllItems();
            CbCiudad.addItem("Sin Especificar");
            break;
            case 1:
            CbCiudad.removeAllItems();
            CbCiudad.addItem("Sin Especificar");
            CbCiudad.addItem("Camilo Ponce Enriquez");
            CbCiudad.addItem("Chordeleg");
            CbCiudad.addItem("Cuenca");
            CbCiudad.addItem("El Pan");
            CbCiudad.addItem("Giron");
            CbCiudad.addItem("Guachapala");
            CbCiudad.addItem("Gualaceo");
            CbCiudad.addItem("Nabon");
            CbCiudad.addItem("Oña");
            CbCiudad.addItem("Paute");
            CbCiudad.addItem("Pucara");
            CbCiudad.addItem("San Fernando");
            CbCiudad.addItem("Santa Isabel");
            CbCiudad.addItem("Sevilla de Oro");
            CbCiudad.addItem("Sigsig");
            break;
            case 2:
            CbCiudad.removeAllItems();
            CbCiudad.addItem("Sin Especificar");
            CbCiudad.addItem("Caluma");
            CbCiudad.addItem("Chillanes");
            CbCiudad.addItem("Chimbo");
            CbCiudad.addItem("Echeandia");
            CbCiudad.addItem("Guaranda");
            CbCiudad.addItem("Las Naves");
            CbCiudad.addItem("San Miguel");
            break;
            case 3:
            CbCiudad.removeAllItems();
            CbCiudad.addItem("Sin Especificar");
            CbCiudad.addItem("Azogues");
            CbCiudad.addItem("Biblian");
            CbCiudad.addItem("Cañar");
            CbCiudad.addItem("Deleg");
            CbCiudad.addItem("El Tambo");
            CbCiudad.addItem("La Troncal");
            CbCiudad.addItem("Suscal");
            break;
            case 4:
            CbCiudad.removeAllItems();
            CbCiudad.addItem("Sin Especificar");
            CbCiudad.addItem("Bolivar");
            CbCiudad.addItem("Espejo");
            CbCiudad.addItem("Huace");
            CbCiudad.addItem("Mira");
            CbCiudad.addItem("Montufar");
            CbCiudad.addItem("Tulcan");
            break;
            case 5:
            CbCiudad.removeAllItems();
            CbCiudad.addItem("Sin Especificar");
            CbCiudad.addItem("Alausi");
            CbCiudad.addItem("Chambo");
            CbCiudad.addItem("Chunchi");
            CbCiudad.addItem("Cumanda");
            CbCiudad.addItem("Guamote");
            CbCiudad.addItem("Guano");
            CbCiudad.addItem("Pallatanga");
            CbCiudad.addItem("Penipe");
            CbCiudad.addItem("Riobamba");
            break;
            case 6:
            CbCiudad.removeAllItems();
            CbCiudad.addItem("Sin Especificar");
            CbCiudad.addItem("La Mana");
            CbCiudad.addItem("Latacunga");
            CbCiudad.addItem("Pangua");
            CbCiudad.addItem("Pujili");
            CbCiudad.addItem("Salcedo");
            CbCiudad.addItem("Saquisili");
            CbCiudad.addItem("Sigchos");
            break;
            case 7:
            CbCiudad.removeAllItems();
            CbCiudad.addItem("Sin Especificar");
            CbCiudad.addItem("Arenillas");
            CbCiudad.addItem("Atagualpa");
            CbCiudad.addItem("Balsas");
            CbCiudad.addItem("Chilla");
            CbCiudad.addItem("El Guabo");
            CbCiudad.addItem("Huaquillas");
            CbCiudad.addItem("Las Lajas");
            CbCiudad.addItem("Machala");
            CbCiudad.addItem("Marcabeli");
            CbCiudad.addItem("Pasaje");
            CbCiudad.addItem("Piñas");
            CbCiudad.addItem("Portovelo");
            CbCiudad.addItem("Santa Rosa");
            CbCiudad.addItem("Zaruma");
            break;
            case 8:
            CbCiudad.removeAllItems();
            CbCiudad.addItem("Sin Especificar");
            CbCiudad.addItem("Atacames");
            CbCiudad.addItem("Eloy Alfaro");
            CbCiudad.addItem("Esmeraldas");
            CbCiudad.addItem("Muisne");
            CbCiudad.addItem("Quininde");
            CbCiudad.addItem("Rioverde");
            CbCiudad.addItem("San Lorenzo");
            break;
            case 9:
            CbCiudad.removeAllItems();
            CbCiudad.addItem("Sin Especificar");
            break;
            case 10:
            CbCiudad.removeAllItems();
            CbCiudad.addItem("Sin Especificar");
            CbCiudad.addItem("Isabela");
            CbCiudad.addItem("San Cristobal");
            CbCiudad.addItem("Santa Cruz");
            break;
            case 11:
            CbCiudad.removeAllItems();
            CbCiudad.addItem("Sin Especificar");
            CbCiudad.addItem("Balao");
            CbCiudad.addItem("Balzar");
            CbCiudad.addItem("Bucay");
            CbCiudad.addItem("Colimes");
            CbCiudad.addItem("Daule");
            CbCiudad.addItem("Duran");
            CbCiudad.addItem("El Empalme");
            CbCiudad.addItem("El Triunfo");
            CbCiudad.addItem("Guayaquil");
            CbCiudad.addItem("Isidro Ayora");
            CbCiudad.addItem("Jujan");
            CbCiudad.addItem("Lomas de Sargentillo");
            CbCiudad.addItem("Marcelino Maridueña");
            CbCiudad.addItem("Milagro");
            CbCiudad.addItem("Naranjal");
            CbCiudad.addItem("Naranjito");
            CbCiudad.addItem("Nobol");
            CbCiudad.addItem("Palestina");
            CbCiudad.addItem("Pedro Carbo");
            CbCiudad.addItem("Playas");
            CbCiudad.addItem("Salitre");
            CbCiudad.addItem("Sanborondon");
            CbCiudad.addItem("Santa Lucia");
            CbCiudad.addItem("Simon Bolivar");
            CbCiudad.addItem("Yaguachi");
            break;
            case 12:
            CbCiudad.removeAllItems();
            CbCiudad.addItem("Sin Especificar");
            CbCiudad.addItem("Anotonio Ante");
            CbCiudad.addItem("Cotacachi");
            CbCiudad.addItem("Otavalo");
            CbCiudad.addItem("Pimampiro");
            CbCiudad.addItem("San Miguel de Urcuqui");
            break;
            case 13:
            CbCiudad.removeAllItems();
            CbCiudad.addItem("Sin Especificar");
            CbCiudad.addItem("Alamor");
            CbCiudad.addItem("Calvas");
            CbCiudad.addItem("Catamayo");
            CbCiudad.addItem("Celica");
            CbCiudad.addItem("Chaguarpamba");
            CbCiudad.addItem("Espindola");
            CbCiudad.addItem("Gonzanama");
            CbCiudad.addItem("Loja");
            CbCiudad.addItem("Macara");
            CbCiudad.addItem("Olmedo");
            CbCiudad.addItem("Paltas");
            CbCiudad.addItem("Pindal");
            CbCiudad.addItem("Puyango");
            CbCiudad.addItem("Quilanga");
            CbCiudad.addItem("Saraguro");
            CbCiudad.addItem("Sozoranga");
            CbCiudad.addItem("Zapotillo");
            break;
            case 14:
            CbCiudad.removeAllItems();
            CbCiudad.addItem("Sin Especificar");
            CbCiudad.addItem("Baba");
            CbCiudad.addItem("Babahoyo");
            CbCiudad.addItem("Buena Fe");
            CbCiudad.addItem("Mocache");
            CbCiudad.addItem("Montalvo");
            CbCiudad.addItem("Palenque");
            CbCiudad.addItem("Pueblo Viejo");
            CbCiudad.addItem("Quevedo");
            CbCiudad.addItem("Quinsaloma");
            CbCiudad.addItem("Urdaneta");
            CbCiudad.addItem("Valencia");
            CbCiudad.addItem("Ventanas");
            CbCiudad.addItem("Vinces");
            break;
            case 15:
            CbCiudad.removeAllItems();
            CbCiudad.addItem("Sin Especificar");
            CbCiudad.addItem("24 de Mayo");
            CbCiudad.addItem("Bolivar");
            CbCiudad.addItem("Calceta");
            CbCiudad.addItem("Chone");
            CbCiudad.addItem("El Carmen");
            CbCiudad.addItem("Flavio Alfaro");
            CbCiudad.addItem("Jama");
            CbCiudad.addItem("Jaramijo");
            CbCiudad.addItem("Jipijapa");
            CbCiudad.addItem("Junin");
            CbCiudad.addItem("Manta");
            CbCiudad.addItem("Montecristi");
            CbCiudad.addItem("Olmedo");
            CbCiudad.addItem("Pajan");
            CbCiudad.addItem("Pedernales");
            CbCiudad.addItem("Pichincha");
            CbCiudad.addItem("Portoviejo");
            CbCiudad.addItem("Puerto Lopez");
            CbCiudad.addItem("Rocafuerte");
            CbCiudad.addItem("San Vicente");
            CbCiudad.addItem("Santa Ana");
            CbCiudad.addItem("Sucre");
            CbCiudad.addItem("Tosagua");
            break;
            case 16:
            CbCiudad.removeAllItems();
            CbCiudad.addItem("Sin Especificar");
            CbCiudad.addItem("Gualaquiza");
            CbCiudad.addItem("Huamboya");
            CbCiudad.addItem("Limon Indanza");
            CbCiudad.addItem("Logroño");
            CbCiudad.addItem("Morona");
            CbCiudad.addItem("Pablo Sexto");
            CbCiudad.addItem("Palora");
            CbCiudad.addItem("San Juan Bosco");
            CbCiudad.addItem("Santiago de Mendez");
            CbCiudad.addItem("Sucua");
            CbCiudad.addItem("Taisha");
            CbCiudad.addItem("Tiwintza");

            break;
            case 17:
            CbCiudad.removeAllItems();
            CbCiudad.addItem("Sin Especificar");
            CbCiudad.addItem("Archidona");
            CbCiudad.addItem("Carlos Julio Arosemena Tola");
            CbCiudad.addItem("El Chaco");
            CbCiudad.addItem("Quijos");
            CbCiudad.addItem("Tena");
            break;
            case 18:
            CbCiudad.removeAllItems();
            CbCiudad.addItem("Sin Especificar");
            CbCiudad.addItem("Aguarico");
            CbCiudad.addItem("Francisco de Orellana");
            CbCiudad.addItem("La Joya de los Sachas");
            CbCiudad.addItem("Loreto");
            break;
            case 19:
            CbCiudad.removeAllItems();
            CbCiudad.addItem("Sin Especificar");
            CbCiudad.addItem("Arajuno");
            CbCiudad.addItem("Mera");
            CbCiudad.addItem("Pastaza");
            CbCiudad.addItem("Santa Clara");
            break;
            case 20:
            CbCiudad.removeAllItems();
            CbCiudad.addItem("Sin Especificar");
            CbCiudad.addItem("Cayambe");
            CbCiudad.addItem("Mejia");
            CbCiudad.addItem("Pedro Moncayo");
            CbCiudad.addItem("Pedro Vicente Maldonado");
            CbCiudad.addItem("Puerto Quito");
            CbCiudad.addItem("Quito");
            CbCiudad.addItem("Rumiñahui");
            CbCiudad.addItem("San Miguel de los Bancos");
            break;
            case 21:
            CbCiudad.removeAllItems();
            CbCiudad.addItem("Sin Especificar");
            CbCiudad.addItem("La Libertad");
            CbCiudad.addItem("Salinas");
            CbCiudad.addItem("Santa Elena");
            break;
            case 22:
            CbCiudad.removeAllItems();
            CbCiudad.addItem("Sin Especificar");
            CbCiudad.addItem("La Concordia");
            CbCiudad.addItem("Santo Domingo");
            break;
            case 23:
            CbCiudad.removeAllItems();
            CbCiudad.addItem("Sin Especificar");
            CbCiudad.addItem("Cascales");
            CbCiudad.addItem("Cuyabeno");
            CbCiudad.addItem("Gonzalo Pizarro");
            CbCiudad.addItem("Lago Agrio");
            CbCiudad.addItem("Putumayo");
            CbCiudad.addItem("Shushufindi");
            CbCiudad.addItem("Sucumbios");
            break;
            case 24:
            CbCiudad.removeAllItems();
            CbCiudad.addItem("Sin Especificar");
            CbCiudad.addItem("Ambato");
            CbCiudad.addItem("Baños");
            CbCiudad.addItem("Cevallos");
            CbCiudad.addItem("Mocha");
            CbCiudad.addItem("Patate");
            CbCiudad.addItem("Pelileo");
            CbCiudad.addItem("Santiago de Pillaro");
            CbCiudad.addItem("Tisaleo");
            break;
            case 25:
            CbCiudad.removeAllItems();
            CbCiudad.addItem("Sin Especificar");
            CbCiudad.addItem("Centinela del Condor");
            CbCiudad.addItem("Chinchipe");
            CbCiudad.addItem("El Pangui");
            CbCiudad.addItem("Nangaritza");
            CbCiudad.addItem("Palanda");
            CbCiudad.addItem("Paquisha");
            CbCiudad.addItem("Yacuambi");
            CbCiudad.addItem("Yantzaza");
            CbCiudad.addItem("Zamora");
            break;
        }
    }//GEN-LAST:event_CbProvinciaActionPerformed

    public JButton getBtnGuardarCli() {
        return BtnGuardarCli;
    }

    public void setBtnGuardarCli(JButton BtnGuardarCli) {
        this.BtnGuardarCli = BtnGuardarCli;
    }
  
    public JComboBox<String> getCbCiudad() {
        return CbCiudad;
    }

    public void setCbCiudad(JComboBox<String> CbCiudad) {
        this.CbCiudad = CbCiudad;
    }

    public JComboBox<String> getCbProvincia() {
        return CbProvincia;
    }

    public void setCbProvincia(JComboBox<String> CbProvincia) {
        this.CbProvincia = CbProvincia;
    }

    public JComboBox<String> getCbTipoId() {
        return CbTipoId;
    }

    public void setCbTipoId(JComboBox<String> CbTipoId) {
        this.CbTipoId = CbTipoId;
    }

    public JTextField getTxtAliasSuc() {
        return TxtAliasSuc;
    }

    public void setTxtAliasSuc(JTextField TxtAliasSuc) {
        this.TxtAliasSuc = TxtAliasSuc;
    }

    public JTextField getTxtCelular() {
        return TxtCelular;
    }

    public void setTxtCelular(JTextField TxtCelular) {
        this.TxtCelular = TxtCelular;
    }

    public JTextField getTxtCodSucursal() {
        return TxtCodSucursal;
    }

    public void setTxtCodSucursal(JTextField TxtCodSucursal) {
        this.TxtCodSucursal = TxtCodSucursal;
    }

    public JTextField getTxtCorreo() {
        return TxtCorreo;
    }

    public void setTxtCorreo(JTextField TxtCorreo) {
        this.TxtCorreo = TxtCorreo;
    }

    public JTextField getTxtId() {
        return TxtId;
    }

    public void setTxtId(JTextField TxtId) {
        this.TxtId = TxtId;
    }

    public JTextField getTxtNombre() {
        return TxtNombre;
    }

    public void setTxtNombre(JTextField TxtNombre) {
        this.TxtNombre = TxtNombre;
    }

    public JTextField getTxtDireccion() {
        return TxtDireccion;
    }

    public void setTxtDireccion(JTextField TxtDireccion) {
        this.TxtDireccion = TxtDireccion;
    }

    public JTextField getTxttelefono() {
        return Txttelefono;
    }

    public void setTxttelefono(JTextField Txttelefono) {
        this.Txttelefono = Txttelefono;
    }

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardarCli;
    private javax.swing.JComboBox<String> CbCiudad;
    private javax.swing.JComboBox<String> CbCiudad1;
    private javax.swing.JComboBox<String> CbProvincia;
    private javax.swing.JComboBox<String> CbTipoId;
    private javax.swing.JTextField TxtAliasSuc;
    private javax.swing.JTextField TxtAliasSuc1;
    private javax.swing.JTextField TxtCelular;
    private javax.swing.JTextField TxtCodSucursal;
    private javax.swing.JTextField TxtCodSucursal1;
    private javax.swing.JTextField TxtCorreo;
    private javax.swing.JTextField TxtDireccion;
    private javax.swing.JTextField TxtId;
    private javax.swing.JTextField TxtId1;
    private javax.swing.JTextField TxtId2;
    private javax.swing.JTextField TxtId3;
    private javax.swing.JTextField TxtId4;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField Txttelefono;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
