/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA.CRUD;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author james
 */
public class VCrearCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form VOpcionesProd
     */
    public VCrearCliente() {
        initComponents();
        quitarBarra();
    }

    
    public void quitarBarra(){
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
    }        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtPrecio1Prod = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtPrecio2Prod = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        CbTipoId = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        CbCateProd = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        TxtSubsiProd = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        CbUnidadProd = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        TxtCodAuxProd = new javax.swing.JTextField();
        BtnGuardarProd = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        TxtPrecio2Prod1 = new javax.swing.JTextField();
        TxtSubsiProd1 = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        TxtSubsiProd2 = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        TxtSubsiProd3 = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(1120, 670));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(33, 49, 91));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 65)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CLIENTES");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(787, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 120));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator7.setForeground(new java.awt.Color(33, 49, 91));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 340, 10));

        jSeparator8.setForeground(new java.awt.Color(33, 49, 91));
        jPanel3.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 180, 10));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setText("Tipo de Identificación:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setText("Identificacion:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        TxtPrecio1Prod.setBorder(null);
        jPanel3.add(TxtPrecio1Prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 220, 30));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel7.setText("Nombres / Razon Social:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 30));

        TxtPrecio2Prod.setBorder(null);
        jPanel3.add(TxtPrecio2Prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 500, 30));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel12.setText("DATOS BASICOS");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        CbTipoId.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        CbTipoId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cedula", "RUC", "Pasaporte", "Identificacion del Exterior", "Placa" }));
        jPanel3.add(CbTipoId, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 190, 30));

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel13.setText("Direccion:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel14.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel14.setText("Alias Sucursal:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel16.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel16.setText("Telefono:");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        CbCateProd.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        CbCateProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Principal", "Prueba", "Juan" }));
        jPanel3.add(CbCateProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 130, 30));

        jLabel19.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel19.setText("Celular:");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, -1));

        jLabel20.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel20.setText("Provincia:");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        TxtSubsiProd.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TxtSubsiProd.setBorder(null);
        jPanel3.add(TxtSubsiProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 180, 30));

        jLabel21.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel21.setText("Correo:");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, -1, -1));

        CbUnidadProd.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        CbUnidadProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "Unidad", "test", "Saco 75Kg", "Saco 5Kg", "Saco 50Kg", "Saco 4Kg", "Saco 45Kg", "Saco 40Kg", "Saco 3Kg", "Saco 35Kg", "Saco 30Kg", "Saco 2Kg", "Saco 25Kg", "Saco 20Kg", "Saco 1Kg", "Saco 15Kg", "Saco 10Kg", "Saco 100Kg", "Paquete de 9", "Paquete de 6", "Paquete de 4", "Paquete de 36", "Paquete de 3", "Paquete de 24", "Paquete de 20", "Paquete de 18", "Paquete de 13", "Paquete de 12", "Paquete de 10", "Metros", "Kilogramo" }));
        jPanel3.add(CbUnidadProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 140, 30));

        jLabel22.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel22.setText("Ciudad:");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, -1, -1));

        TxtCodAuxProd.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TxtCodAuxProd.setBorder(null);
        jPanel3.add(TxtCodAuxProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 100, 30));

        BtnGuardarProd.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        BtnGuardarProd.setText("Guardar");
        jPanel3.add(BtnGuardarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 420, 90, 40));

        jSeparator9.setForeground(new java.awt.Color(33, 49, 91));
        jPanel3.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 220, 10));

        jSeparator10.setForeground(new java.awt.Color(33, 49, 91));
        jPanel3.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 100, 10));

        jLabel17.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel17.setText("Codigo Sucursal:");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, -1));

        TxtPrecio2Prod1.setBorder(null);
        jPanel3.add(TxtPrecio2Prod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 340, 30));

        TxtSubsiProd1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TxtSubsiProd1.setBorder(null);
        jPanel3.add(TxtSubsiProd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 170, 30));

        jSeparator12.setForeground(new java.awt.Color(33, 49, 91));
        jPanel3.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 170, 10));

        TxtSubsiProd2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TxtSubsiProd2.setBorder(null);
        jPanel3.add(TxtSubsiProd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 160, 30));

        jSeparator13.setForeground(new java.awt.Color(33, 49, 91));
        jPanel3.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 160, 10));

        TxtSubsiProd3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        TxtSubsiProd3.setBorder(null);
        jPanel3.add(TxtSubsiProd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, 330, 30));

        jSeparator14.setForeground(new java.awt.Color(33, 49, 91));
        jPanel3.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 330, 10));

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel15.setText("MATRIZ");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jSeparator15.setForeground(new java.awt.Color(33, 49, 91));
        jPanel3.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 500, 10));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 1070, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardarProd;
    private javax.swing.JComboBox<String> CbCateProd;
    private javax.swing.JComboBox<String> CbTipoId;
    private javax.swing.JComboBox<String> CbUnidadProd;
    private javax.swing.JTextField TxtCodAuxProd;
    private javax.swing.JTextField TxtPrecio1Prod;
    private javax.swing.JTextField TxtPrecio2Prod;
    private javax.swing.JTextField TxtPrecio2Prod1;
    private javax.swing.JTextField TxtSubsiProd;
    private javax.swing.JTextField TxtSubsiProd1;
    private javax.swing.JTextField TxtSubsiProd2;
    private javax.swing.JTextField TxtSubsiProd3;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
