/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA.CRUD;

import javax.swing.JLabel;

/**
 *
 * @author james
 */
public class VOpcionesProd extends javax.swing.JInternalFrame {

    /**
     * Creates new form VOpcionesProd
     */
    public VOpcionesProd() {
        initComponents();
        quitarBarra();
    }

    
    public void quitarBarra(){
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
    }        

    public JLabel getLbImportar() {
        return LbImportar;
    }

    public void setLbImportar(JLabel LbImportar) {
        this.LbImportar = LbImportar;
    }

    public JLabel getLbIngresoM() {
        return LbIngresoM;
    }

    public void setLbIngresoM(JLabel LbIngresoM) {
        this.LbIngresoM = LbIngresoM;
    }

    public JLabel getLbKardex() {
        return LbKardex;
    }

    public void setLbKardex(JLabel LbKardex) {
        this.LbKardex = LbKardex;
    }

    public JLabel getLbMostrar() {
        return LbMostrar;
    }

    public void setLbMostrar(JLabel LbMostrar) {
        this.LbMostrar = LbMostrar;
    }

    public JLabel getLbNuev() {
        return LbNuev;
    }

    public void setLbNuev(JLabel LbNuev) {
        this.LbNuev = LbNuev;
    }

    public JLabel getLbReportes() {
        return LbReportes;
    }

    public void setLbReportes(JLabel LbReportes) {
        this.LbReportes = LbReportes;
    }

    public JLabel getLbSalidaM() {
        return LbSalidaM;
    }

    public void setLbSalidaM(JLabel LbSalidaM) {
        this.LbSalidaM = LbSalidaM;
    }

    public JLabel getLbTransferencia() {
        return LbTransferencia;
    }

    public void setLbTransferencia(JLabel LbTransferencia) {
        this.LbTransferencia = LbTransferencia;
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LbNuev = new javax.swing.JLabel();
        LbIngresoM = new javax.swing.JLabel();
        LbSalidaM = new javax.swing.JLabel();
        LbImportar = new javax.swing.JLabel();
        LbReportes = new javax.swing.JLabel();
        LbMostrar = new javax.swing.JLabel();
        LbKardex = new javax.swing.JLabel();
        LbTransferencia = new javax.swing.JLabel();
        LbFondo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1120, 670));

        jPanel1.setBackground(new java.awt.Color(225, 235, 245));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbNuev.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        LbNuev.setForeground(new java.awt.Color(255, 255, 255));
        LbNuev.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbNuev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/ICONOS/Add.png"))); // NOI18N
        LbNuev.setText("Nuevo");
        LbNuev.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbNuev.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LbNuev.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(LbNuev, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 200, 190));

        LbIngresoM.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        LbIngresoM.setForeground(new java.awt.Color(255, 255, 255));
        LbIngresoM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbIngresoM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/ICONOS/Ingreso.png"))); // NOI18N
        LbIngresoM.setText("Ingreso de Mercaderia");
        LbIngresoM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbIngresoM.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LbIngresoM.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(LbIngresoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 260, 190));

        LbSalidaM.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        LbSalidaM.setForeground(new java.awt.Color(255, 255, 255));
        LbSalidaM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbSalidaM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/ICONOS/SalidaD.png"))); // NOI18N
        LbSalidaM.setText("Salida de Mercaderia");
        LbSalidaM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbSalidaM.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LbSalidaM.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(LbSalidaM, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 70, 250, 190));

        LbImportar.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        LbImportar.setForeground(new java.awt.Color(255, 255, 255));
        LbImportar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbImportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/ICONOS/Importar.png"))); // NOI18N
        LbImportar.setText("<html> <center> Importar Productos </center>  <html>");
        LbImportar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbImportar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LbImportar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(LbImportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 180, 210));

        LbReportes.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        LbReportes.setForeground(new java.awt.Color(255, 255, 255));
        LbReportes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/ICONOS/Reportes.png"))); // NOI18N
        LbReportes.setText("Reportes");
        LbReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbReportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LbReportes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(LbReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 180, 210));

        LbMostrar.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        LbMostrar.setForeground(new java.awt.Color(255, 255, 255));
        LbMostrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/ICONOS/Read.png"))); // NOI18N
        LbMostrar.setText("Ver Todos");
        LbMostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbMostrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LbMostrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(LbMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 180, 190));

        LbKardex.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        LbKardex.setForeground(new java.awt.Color(255, 255, 255));
        LbKardex.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbKardex.setText("Kardex");
        LbKardex.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbKardex.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LbKardex.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(LbKardex, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 320, 250, 190));

        LbTransferencia.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        LbTransferencia.setForeground(new java.awt.Color(255, 255, 255));
        LbTransferencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbTransferencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/ICONOS/Transferencia.png"))); // NOI18N
        LbTransferencia.setText("<html> <center> Transferencia Mercaderia </center>  <html>");
        LbTransferencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbTransferencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LbTransferencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(LbTransferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 180, 210));

        LbFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/ICONOS/FondoOpciones.jpg"))); // NOI18N
        LbFondo.setText("jLabel1");
        LbFondo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(LbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbFondo;
    private javax.swing.JLabel LbImportar;
    private javax.swing.JLabel LbIngresoM;
    private javax.swing.JLabel LbKardex;
    private javax.swing.JLabel LbMostrar;
    private javax.swing.JLabel LbNuev;
    private javax.swing.JLabel LbReportes;
    private javax.swing.JLabel LbSalidaM;
    private javax.swing.JLabel LbTransferencia;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
