/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA.CRUD;

import javax.swing.JLabel;

/**
 *
 * @author james
 */
public class VOpcionesComp extends javax.swing.JInternalFrame {

    /**
     * Creates new form VOpcionesProd
     */
    public VOpcionesComp() {
        initComponents();
        quitarBarra();
    }

    public void quitarBarra(){
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
    }           

    public JLabel getLbFondo() {
        return LbFondo;
    }

    public void setLbFondo(JLabel LbFondo) {
        this.LbFondo = LbFondo;
    }

    public JLabel getLbNFact() {
        return LbNFact;
    }

    public void setLbNFact(JLabel LbNFact) {
        this.LbNFact = LbNFact;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LbNProv = new javax.swing.JLabel();
        LbMostrarTrans = new javax.swing.JLabel();
        LbNFact = new javax.swing.JLabel();
        LbMostrarCli = new javax.swing.JLabel();
        LbMostrarProv = new javax.swing.JLabel();
        LbNTrans = new javax.swing.JLabel();
        LbNTrans1 = new javax.swing.JLabel();
        LbMostrarTrans1 = new javax.swing.JLabel();
        LbNProv1 = new javax.swing.JLabel();
        LbMostrarProv1 = new javax.swing.JLabel();
        LbNTrans2 = new javax.swing.JLabel();
        LbMostrarTrans2 = new javax.swing.JLabel();
        LbFondo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1120, 670));

        jPanel1.setBackground(new java.awt.Color(225, 235, 245));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbNProv.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        LbNProv.setForeground(new java.awt.Color(255, 255, 255));
        LbNProv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbNProv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/ICONOS/AddProve.png"))); // NOI18N
        LbNProv.setText("Nueva Retencion");
        LbNProv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbNProv.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LbNProv.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(LbNProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 210, 190));

        LbMostrarTrans.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        LbMostrarTrans.setForeground(new java.awt.Color(255, 255, 255));
        LbMostrarTrans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbMostrarTrans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/ICONOS/Read.png"))); // NOI18N
        LbMostrarTrans.setText("Ver Todos");
        LbMostrarTrans.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbMostrarTrans.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LbMostrarTrans.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(LbMostrarTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, 180, 190));

        LbNFact.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        LbNFact.setForeground(new java.awt.Color(255, 255, 255));
        LbNFact.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbNFact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/ICONOS/AddCli.png"))); // NOI18N
        LbNFact.setText(" Nueva Factura");
        LbNFact.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbNFact.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LbNFact.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(LbNFact, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 200, 190));

        LbMostrarCli.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        LbMostrarCli.setForeground(new java.awt.Color(255, 255, 255));
        LbMostrarCli.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbMostrarCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/ICONOS/Read.png"))); // NOI18N
        LbMostrarCli.setText("Ver Todos");
        LbMostrarCli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbMostrarCli.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LbMostrarCli.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(LbMostrarCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 180, 190));

        LbMostrarProv.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        LbMostrarProv.setForeground(new java.awt.Color(255, 255, 255));
        LbMostrarProv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbMostrarProv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/ICONOS/Read.png"))); // NOI18N
        LbMostrarProv.setText("Ver Todos");
        LbMostrarProv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbMostrarProv.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LbMostrarProv.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(LbMostrarProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 180, 190));

        LbNTrans.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        LbNTrans.setForeground(new java.awt.Color(255, 255, 255));
        LbNTrans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbNTrans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/ICONOS/AddTrans.png"))); // NOI18N
        LbNTrans.setText("Nueva Nota de credito");
        LbNTrans.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbNTrans.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LbNTrans.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(LbNTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 270, 190));

        LbNTrans1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        LbNTrans1.setForeground(new java.awt.Color(255, 255, 255));
        LbNTrans1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbNTrans1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/ICONOS/AddTrans.png"))); // NOI18N
        LbNTrans1.setText("Nueva Guia");
        LbNTrans1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbNTrans1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LbNTrans1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(LbNTrans1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 250, 190));

        LbMostrarTrans1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        LbMostrarTrans1.setForeground(new java.awt.Color(255, 255, 255));
        LbMostrarTrans1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbMostrarTrans1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/ICONOS/Read.png"))); // NOI18N
        LbMostrarTrans1.setText("Ver Todos");
        LbMostrarTrans1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbMostrarTrans1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LbMostrarTrans1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(LbMostrarTrans1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 220, 180, 190));

        LbNProv1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        LbNProv1.setForeground(new java.awt.Color(255, 255, 255));
        LbNProv1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbNProv1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/ICONOS/AddProve.png"))); // NOI18N
        LbNProv1.setText(" Nuevo Notas de Debito");
        LbNProv1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbNProv1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LbNProv1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(LbNProv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 270, 190));

        LbMostrarProv1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        LbMostrarProv1.setForeground(new java.awt.Color(255, 255, 255));
        LbMostrarProv1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbMostrarProv1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/ICONOS/Read.png"))); // NOI18N
        LbMostrarProv1.setText("Ver Todos");
        LbMostrarProv1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbMostrarProv1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LbMostrarProv1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(LbMostrarProv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 180, 190));

        LbNTrans2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        LbNTrans2.setForeground(new java.awt.Color(255, 255, 255));
        LbNTrans2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbNTrans2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/ICONOS/AddTrans.png"))); // NOI18N
        LbNTrans2.setText(" Nueva Liquidacion de Compra");
        LbNTrans2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbNTrans2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LbNTrans2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(LbNTrans2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, 360, 190));

        LbMostrarTrans2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        LbMostrarTrans2.setForeground(new java.awt.Color(255, 255, 255));
        LbMostrarTrans2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbMostrarTrans2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/ICONOS/Read.png"))); // NOI18N
        LbMostrarTrans2.setText("Ver Todos");
        LbMostrarTrans2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbMostrarTrans2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LbMostrarTrans2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(LbMostrarTrans2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 420, 180, 190));

        LbFondo.setBackground(new java.awt.Color(255, 255, 255));
        LbFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/ICONOS/FondoOpciones.jpg"))); // NOI18N
        LbFondo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(LbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbFondo;
    private javax.swing.JLabel LbMostrarCli;
    private javax.swing.JLabel LbMostrarProv;
    private javax.swing.JLabel LbMostrarProv1;
    private javax.swing.JLabel LbMostrarTrans;
    private javax.swing.JLabel LbMostrarTrans1;
    private javax.swing.JLabel LbMostrarTrans2;
    private javax.swing.JLabel LbNFact;
    private javax.swing.JLabel LbNProv;
    private javax.swing.JLabel LbNProv1;
    private javax.swing.JLabel LbNTrans;
    private javax.swing.JLabel LbNTrans1;
    private javax.swing.JLabel LbNTrans2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
